<?php

/**
 * Factory method for the HttpClient. Use this if you don't want to select a
 * Http client delegate yourself.
 *
 * @param object $authentication
 * @param object $formatter
 * @param object $request_alter
 * @param object $delegate
 * @return HttpClient
 */
function http_client($authentication = NULL, $formatter = NULL, $request_alter = NULL, $delegate = NULL) {
  // Allow other modules to specify the delegate.
  if (!$delegate) {
    $delegates = array();
    foreach (module_implements('http_client_delegates') as $module) {
      $res = call_user_func($module . '_http_client_delegates');
      if (is_array($res)) {
        $delegates = $res + $delegates;
      }
    }
    backdrop_alter('http_client_delegates', $delegates);
    if (!empty($delegates)) {
      $delegate = array_pop($delegates);
    }
  }
  return new HttpClient($authentication, $formatter, $request_alter, $delegate);
}

/**
 * Implements hook_http_client_delegates().
 */
function http_client_http_client_delegates() {
  $delegates = array();
  if (function_exists('curl_init')) {
    $delegates['curl'] = new HttpClientCurlDelegate();
  }
  return $delegates;
}

/**
 * Implements hook_autoload_info().
 */
function http_client_autoload_info() {
  return array(
    'HttpClient' => 'includes/HttpClient.inc',
    'HttpClientDelegate' => 'includes/HttpClient.inc',
    'HttpClientException' => 'includes/HttpClient.inc',
    'HttpClientBaseFormatter' => 'includes/HttpClient.inc',
    'HttpClientCompositeFormatter' => 'includes/HttpClient.inc',
    'HttpClientFormatter' => 'includes/HttpClient.inc',
    'HttpClientAuthentication' => 'includes/HttpClient.inc',
    'HttpClientRequest' => 'includes/HttpClient.inc',
    'HttpClientCurlDelegate' => 'includes/HttpClientCurlDelegate.inc',
    'HttpClientBasicAuth' => 'includes/auth/basic/HttpClientBasicAuth.inc',
    'HttpClientXMLFormatter' => 'includes/formatter/HttpClientXMLFormatter.inc',
  );
}
